# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('abbr', models.CharField(blank=True, default='', max_length=10, null=True, unique=True, verbose_name='Abbreviation')),
                ('found_date', models.DateTimeField(verbose_name='Date Founded')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Ended')),
                ('summary', models.TextField(default='', max_length=256, verbose_name='Summary')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('members', models.IntegerField(default=0, verbose_name='Number of Members')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Organization Email')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public')),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last Modified')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'RSO',
                'verbose_name_plural': 'RSOs',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Tag')),
                ('breadth', models.CharField(choices=[('B', 'BROAD'), ('S', 'SPECIFIC'), ('N', 'NICHE')], default='N', max_length=1, verbose_name='Breadth')),
                ('parents', models.ManyToManyField(blank=True, related_name='Parents', to='app.Tag')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set([('name', 'abbr')]),
        ),
    ]
