# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('organizations', models.IntegerField(default=0, verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('abbr', models.CharField(default='', max_length=10, unique=True, verbose_name='Abbreviation')),
                ('found_date', models.DateField(verbose_name='Date Founded')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('members', models.IntegerField(default=0, verbose_name='Number of Members')),
            ],
            options={
                'verbose_name': 'RSO',
                'verbose_name_plural': 'RSOs',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set([('name', 'abbr')]),
        ),
    ]
