# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='parents',
            field=models.ManyToManyField(related_name='_tag_parents_+', to='app.Tag'),
        ),
    ]
