# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tag_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='_tag_parents_+', to='app.Tag'),
        ),
    ]
